all: algebra-1-2019-preguntas.pdf algebra-1-2019-suficiencia.pdf

algebra-1-2019-preguntas.pdf:
	pdflatex algebra-1-2019-preguntas

algebra-1-2019-suficiencia.pdf:
	pdflatex algebra-1-2019-suficiencia

clean:
	rm -f *.aux *.log *.out *.pdf
